@url = https://supreme-space-meme-g496xxvw47xcwv7p-8080.app.github.dev

GET {{url}}/livros

###
POST {{url}}/livros
Content-Type: application/json

{
    "titulo": "Teste",
    "id_genero": 1,
    "autores" : "Eu mesmo"
}

###
GET {{url}}/livros/2

###
PUT {{url}}/livros/2
Content-Type: application/json

{
    "titulo": "Teste",
    "generos" : "Teste",
    "autores" : "Teste"
}

###
DELETE {{url}}/livros/2